Repository BeaverHealth-Vulnerable-Web-App/BeaverHealth-Vulnerable-Web-App, pull requests merged in 2025-03, with the labels that each got.

#95 UI updates
  app/Http/Controllers/AddRecordsController.php
  app/Http/Controllers/AuthenticatedSessionController.php
  app/Http/Controllers/PasswordController.php
  app/Http/Controllers/PatientInfoController.php
  app/Http/Controllers/RegisteredUserController.php
  app/Http/Requests/ProfileUpdateRequest.php
  app/View/Components/StatusMessage.php
  app/View/Components/Table.php
  app/View/Components/TableRow.php
  resources/js/admin.js
  resources/js/utils.js
  resources/js/vulnerability_toggles.js
  resources/views/admin.blade.php
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/reset-password.blade.php
  resources/views/components/application-logo.blade.php
  resources/views/components/danger-button.blade.php
  resources/views/components/dropdown-link.blade.php
  resources/views/components/dropdown.blade.php
  resources/views/components/modal.blade.php
  resources/views/components/nav-link.blade.php
  resources/views/components/responsive-nav-link.blade.php
  resources/views/components/secondary-button.blade.php
  resources/views/components/sidebar.blade.php
  resources/views/components/status-message.blade.php
  resources/views/components/table-row.blade.php
  resources/views/components/table.blade.php
  resources/views/feedback/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/sidebar.blade.php
  resources/views/patients/index.blade.php
  resources/views/patients/info.blade.php
  resources/views/profile/change-password.blade.php
  resources/views/records/add.blade.php
  resources/views/records/request.blade.php
  resources/views/vuln_toggles/index.blade.php
  routes/web.php
  vite.config.js
Labels: refactor

#98 Secure access control
  app/Http/Controllers/AddRecordsController.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/FeedbackController.php
  app/Http/Controllers/PasswordController.php
  app/Http/Controllers/RegisteredUserController.php
  app/Http/Middleware/CheckPermissionMiddleware.php
  app/Models/User.php
  app/Services/UserRoleService.php
  bootstrap/app.php
  database/factories/UserFactory.php
  database/migrations/2024_11_19_153826_create_user_table.php
  database/seeders/UserSeeder.php
  resources/js/admin.js
  resources/js/sidebar.js
  resources/js/utils.js
  resources/views/admin.blade.php
  resources/views/feedback/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/profile/change-password.blade.php
  resources/views/records/add.blade.php
  resources/views/vuln_toggles/index.blade.php
  routes/web.php
  tests/Feature/AccessControlFeatureTest.php
  tests/Feature/VulnTogglesFeatureTest.php
Labels: Feature

#99 Secure Patient Feedback
  app/Http/Controllers/FeedbackController.php
  app/Models/PatientFeedback.php
  app/Services/FeedbackService.php
  database/migrations/2024_11_19_154059_create_patient_feedback_table.php
Labels: Feature

#103 Change Password- Insecure version
  app/Http/Controllers/PasswordController.php
  app/Http/Requests/ChangePasswordRequest.php
  app/Services/ChangePasswordService.php
  resources/views/profile/change-password.blade.php
Labels: Feature

#102 Add Dashboard Content
  README.md
  resources/js/vulnerability_toggles.js
  resources/views/dashboard.blade.php
  resources/views/vuln_toggles/index.blade.php
Labels: refactor, enhancement

#105 Secure Versions of Add & Request Medical Records Pages
  Dockerfile
  app/Http/Controllers/AddRecordsController.php
  app/Http/Controllers/RequestRecordsController.php
  app/Services/PatientRecordService.php
  docker-compose.dev.yaml
  resources/js/records.js
  resources/js/utils.js
  resources/views/records/add.blade.php
  resources/views/records/request.blade.php
  vite.config.js
Labels: Feature
