Repository BeaverHealth-Vulnerable-Web-App/BeaverHealth-Vulnerable-Web-App, pull requests merged in 2025-02, with the labels that each got.

#54 testing: Creating vulnerability toggles feature tests
  .github/workflows/ci.yaml
  README.md
  app/Http/Controllers/VulnerabilityTogglesController.php
  app/Http/Requests/VulnTogglesRequest.php
  app/Services/VulnTogglesService.php
  composer.json
  composer.lock
  tests/Feature/ExampleTest.php
  tests/Feature/FeedbackFeatureTest.php
  tests/Feature/FeedbackTest.php
  tests/Feature/VulnTogglesFeatureTest.php
  tests/Pest.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
Labels: testing

#57 Auth feature tests and Dockerfile refactor
  Dockerfile
  apache-laravel.conf
  tests/Feature/AuthFeatureTest.php
  tests/TestCase.php
Labels: testing

#58 Enforce PSR-12 Standards
  CONTRIBUTING.md
  app/Http/Controllers/AddRecordsController.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Models/Patient.php
  app/Models/PatientFeedback.php
  app/Models/User.php
  bootstrap/app.php
  config/cache.php
  config/filesystems.php
  config/logging.php
  config/session.php
  database/factories/PatientFactory.php
  database/migrations/0001_01_01_000001_create_cache_table.php
  database/migrations/2024_11_19_153826_create_user_table.php
  database/migrations/2024_11_19_154054_create_patient_table.php
  database/migrations/2024_11_19_154059_create_patient_feedback_table.php
  database/seeders/DatabaseSeeder.php
  phpcs.xml
  routes/web.php
  tests/Feature/AuthFeatureTest.php
  tests/Feature/FeedbackFeatureTest.php
  tests/Feature/VulnTogglesFeatureTest.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
Labels: chore

#64 Fix setup process and automate deployment
  .dockerignore
  .env
  Dockerfile
  README.md
  database/migrations/2024_11_19_153826_create_user_table.php
  database/migrations/2024_11_19_154054_create_patient_table.php
  database/migrations/2024_11_19_154059_create_patient_feedback_table.php
  docker-compose.dev.yaml
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  setup.sh
Labels: devops

#82 Update CI
  .env
  .github/workflows/ci.yaml
  composer.json
  composer.lock
  docker-compose.ci.yaml
Labels: devops

#69 Access control feature tests
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Requests/UpdateUserRoleRequest.php
  app/Services/UserRoleService.php
  routes/web.php
  tests/Feature/AccessControlFeatureTest.php
Labels: testing

#68 Fully Developed Add & Request Pages
  app/Http/Controllers/AddRecordsController.php
  app/Http/Controllers/RequestRecordsController.php
  app/Http/Requests/Records/PatientSearchRequest.php
  app/Http/Requests/Records/StoreRecordRequest.php
  app/Models/Patient.php
  app/Models/PatientFile.php
  app/Presenters/FilePresenter.php
  app/Services/PatientRecordService.php
  database/migrations/2025_02_01_021319_create_patient_files_table.php
  resources/views/components/patient-dropdown.blade.php
  resources/views/records/add.blade.php
  resources/views/records/request.blade.php
  routes/web.php
Labels: Feature

#85 Feedback Page Refactor
  app/Http/Controllers/FeedbackController.php
  app/Http/Requests/FeedbackCommentRequest.php
  app/Http/Requests/FeedbackSearchRequest.php
  app/Services/FeedbackService.php
  resources/views/feedback/index.blade.php
  routes/web.php
  tests/Feature/FeedbackFeatureTest.php
Labels: refactor, enhancement

#94 Add pre-commit and pre-push hooks
  .gitignore
  composer.json
  composer.lock
Labels: devops
