Repository BeaverHealth-Vulnerable-Web-App/BeaverHealth-Vulnerable-Web-App, pull requests merged in 2025-04, with the labels that each got.

#121 Expand Testing of Patient Feedback Page
  app/Http/Requests/FeedbackCommentRequest.php
  tests/Feature/FeedbackFeatureTest.php
  tests/Unit/ExampleTest.php
  tests/Unit/FeedbackUnitTest.php
Labels: testing

#124 Prod hardening
  app/Http/Middleware/AjaxMiddleware.php
  app/Http/Middleware/LoginPageRateLimiter.php
  app/Http/Middleware/TrustProxiesMiddleware.php
  app/Providers/AppServiceProvider.php
  bootstrap/app.php
  database/seeders/UserSeeder.php
  routes/web.php
Labels: bug, infrastructure, hardening

#125 App reset feature
  app/Http/Controllers/AppResetController.php
  resources/views/components/confirm-reset.blade.php
  resources/views/layouts/sidebar.blade.php
  routes/web.php
Labels: Feature

#123 Logging
  .env.example
  app/Http/Controllers/AppResetController.php
  app/Http/Middleware/AjaxMiddleware.php
  app/Http/Middleware/CheckPermissionMiddleware.php
  app/Http/Middleware/LogUserActivityMiddleware.php
  app/Http/Middleware/LoginPageRateLimiter.php
  app/Http/Middleware/TrustProxiesMiddleware.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Providers/AppServiceProvider.php
  app/Services/ChangePasswordService.php
  app/Services/FeedbackService.php
  app/Services/PatientRecordService.php
  app/Services/UserActivityLogger.php
  app/Services/UserRoleService.php
  app/Services/VulnTogglesService.php
  bootstrap/app.php
  config/app.php
  database/seeders/UserSeeder.php
  resources/views/components/confirm-reset.blade.php
  resources/views/layouts/sidebar.blade.php
  routes/web.php
  tests/Unit/FeedbackUnitTest.php
Labels: refactor, infrastructure
