Repository BeaverHealth-Vulnerable-Web-App/BeaverHealth-Vulnerable-Web-App, pull requests merged in 2025-05, with the labels that each got.

#133 A few more demo setup changes
  app/Http/Middleware/LogUserActivityMiddleware.php
  app/Http/Middleware/TrustProxiesMiddleware.php
  app/Providers/AppServiceProvider.php
  config/session.php
  database/seeders/UserSeeder.php
  resources/views/auth/login.blade.php
  routes/web.php
Labels: infrastructure

#134 Small content updates
  resources/views/dashboard.blade.php
  resources/views/vuln_toggles/index.blade.php
Labels: chore

#135 Feedback Search Bug Fix
  app/Http/Requests/FeedbackCommentRequest.php
Labels: bug

#138 Make rate limiters configurable
  app/Http/Controllers/AuthenticatedSessionController.php
  app/Http/Middleware/LoginPageRateLimiter.php
  app/Http/Requests/Auth/LoginRequest.php
  config/auth.php
  tests/Feature/AuthFeatureTest.php
Labels: enhancement

#137 UI Tweaks
  app/Http/Controllers/AddRecordsController.php
  app/Http/Controllers/FeedbackController.php
  app/Http/Controllers/RequestRecordsController.php
  app/Services/PatientRecordService.php
  resources/views/components/patient-dropdown.blade.php
  resources/views/records/add.blade.php
  resources/views/records/request.blade.php
Labels: enhancement

#146 File Upload Feature Tests
  tests/Feature/AddRecordsFeatureTest.php
Labels: testing

#151 Command Injection Fix
  app/Services/PatientRecordService.php
  resources/views/layouts/app.blade.php
Labels: bug

#147 Fix Patient Information details page
  app/Http/Controllers/PatientInfoController.php
  app/Http/Middleware/CheckPermissionMiddleware.php
  resources/views/layouts/sidebar.blade.php
  resources/views/patients/details.blade.php
  resources/views/patients/index.blade.php
  routes/web.php
Labels: bug

#148 Fix logout force browse bug
  bootstrap/app.php
Labels: bug

#149 Add pagination to Patient Feedback page
  app/Http/Controllers/FeedbackController.php
  app/Services/FeedbackService.php
  resources/views/feedback/index.blade.php
  routes/web.php
  tests/Feature/FeedbackFeatureTest.php
Labels: bug
